package com.puzzlang.runtime;

import com.puzzlang.runtime.builtins.IntegerBuiltins;
import com.puzzlang.runtime.builtins.MathBuiltins;
import com.puzzlang.runtime.builtins.RangeBuiltins;

/**
 * PuzzRuntime — dynamic dispatch for all runtime operations.
 *
 * All methods take Object and return Object so they work with
 * INVOKESTATIC from our generated bytecode.
 *
 * Method dispatch is delegated to MethodRegistry for extensibility.
 * Global function calls are delegated to MathBuiltins.
 *
 * Also handles String and PuzzList method calls directly.
 */
public class PuzzRuntime {

    // Shared registry instance (initialized lazily)
    private static volatile MethodRegistry registry;

    /**
     * Gets (or creates) the shared method registry.
     */
    public static MethodRegistry getRegistry() {
        if (registry == null) {
            synchronized (PuzzRuntime.class) {
                if (registry == null) {
                    registry = createDefaultRegistry();
                }
            }
        }
        return registry;
    }

    /**
     * Allows replacing the registry (useful for testing or custom configurations).
     */
    public static void setRegistry(MethodRegistry newRegistry) {
        synchronized (PuzzRuntime.class) {
            registry = newRegistry;
        }
    }

    private static MethodRegistry createDefaultRegistry() {
        MethodRegistry reg = new MethodRegistry();
        RangeBuiltins.register(reg);
        IntegerBuiltins.register(reg);  // NEW: Integer methods
        return reg;
    }

    // ── Range construction ────────────────────────────────────────────────────

    /** Called for  start..end  (exclusive) */
    public static Object makeRange(Object start, Object end) {
        return new PuzzRange(toInt(start), toInt(end), false);
    }

    /** Called for  start..=end  (inclusive) */
    public static Object makeRangeInclusive(Object start, Object end) {
        return new PuzzRange(toInt(start), toInt(end), true);
    }

    // ── Global function dispatch ──────────────────────────────────────────────

    /**
     * Dispatches global function calls: name(arg0, arg1, ...)
     *
     * Called by bytecode for FunctionCall expressions.
     */
    public static Object callFunction(String name, Object... args) {
        return MathBuiltins.call(name, args);
    }

    // ── Method dispatch ───────────────────────────────────────────────────────

    /**
     * Dispatches receiver.method(args) calls.
     *
     * Handles:
     *   - String methods (lines, paragraphs, split, trim, etc.)
     *   - PuzzList methods (count, first, last, get, join, etc.)
     *   - Integer methods (digits, is_prime, gcd, etc.) via MethodRegistry
     *   - PuzzRange methods (via MethodRegistry)
     */
    public static Object callMethod(Object receiver, String method, Object... args) {
        // ── String methods ────────────────────────────────────────────────
        if (receiver instanceof String str) {
            return switch (method) {
                case "lines"      -> PuzzString.lines(str);
                case "paragraphs" -> PuzzString.paragraphs(str);
                case "split"      -> PuzzString.split(str, toString(args[0]));
                case "words"      -> PuzzString.words(str);
                case "chars"      -> PuzzString.chars(str);
                case "trim"       -> str.trim();
                case "length"     -> str.length();
                case "count"      -> countSubstring(str, toString(args[0]));
                case "toInt"      -> PuzzString.toInt(str);
                case "to_int"     -> PuzzString.toInt(str);
                case "upper"      -> str.toUpperCase();
                case "lower"      -> str.toLowerCase();
                case "startsWith" -> PuzzString.startsWith(str, toString(args[0]));
                case "starts_with" -> PuzzString.startsWith(str, toString(args[0]));
                case "endsWith"   -> PuzzString.endsWith(str, toString(args[0]));
                case "ends_with"  -> PuzzString.endsWith(str, toString(args[0]));
                case "contains"   -> PuzzString.contains(str, toString(args[0]));
                case "replace"    -> PuzzString.replace(str, toString(args[0]), toString(args[1]));
                case "isEmpty"    -> str.isEmpty();
                case "is_empty"   -> str.isEmpty();
                case "get"        -> String.valueOf(str.charAt(toInt(args[0])));
                case "substring"  -> {
                    int start = toInt(args[0]);
                    if (args.length > 1) {
                        yield str.substring(start, toInt(args[1]));
                    }
                    yield str.substring(start);
                }
                case "from_base"  -> {
                    int base = toInt(args[0]);
                    if (base < 2 || base > 36) {
                        throw new PuzzLangException("from_base requires base between 2 and 36, got %d", base);
                    }
                    yield Long.parseLong(str, base);
                }
                case "reverse"    -> new StringBuilder(str).reverse().toString();
                case "repeat"     -> str.repeat(toInt(args[0]));
                default -> throw new PuzzLangException("String has no method '%s'", method);
            };
        }

        // ── PuzzList methods ──────────────────────────────────────────────
        if (receiver instanceof PuzzList list) {
            return switch (method) {
                case "count" -> {
                    // count() returns size, count(value) returns occurrences
                    if (args.length == 0) {
                        yield (long) list.size();
                    } else {
                        yield (long) list.countOccurrences(args[0]);
                    }
                }
                case "length"   -> (long) list.size();
                case "size"     -> (long) list.size();
                case "first"    -> list.first();
                case "last"     -> list.last();
                case "get"      -> list.get(toInt(args[0]));
                case "join"     -> list.join(toString(args[0]));
                case "isEmpty"  -> list.isEmpty();
                case "is_empty" -> list.isEmpty();
                case "reversed" -> list.reversed();
                case "contains" -> list.contains(args[0]);
                case "indexOf"  -> list.indexOf(args[0]);
                case "index_of" -> list.indexOf(args[0]);
                case "sum"      -> listSum(list);
                case "product"  -> listProduct(list);
                case "min"      -> listMin(list);
                case "max"      -> listMax(list);
                case "sorted"   -> list.sorted();
                case "unique"   -> list.unique();
                default -> throw new PuzzLangException("List has no method '%s'", method);
            };
        }

        // ── Delegate to MethodRegistry for other types (PuzzRange, Integer, Long, etc.)
        return getRegistry().dispatch(receiver, method, args);
    }

    // ── List aggregation helpers ──────────────────────────────────────────────

    private static int countSubstring(String str, String sub) {
        if (sub.isEmpty()) return 0;
        int count = 0;
        int idx = 0;
        while ((idx = str.indexOf(sub, idx)) != -1) {
            count++;
            idx += sub.length();
        }
        return count;
    }

    private static long listSum(PuzzList list) {
        long sum = 0;
        for (int i = 0; i < list.size(); i++) {
            sum += toLong(list.get(i));
        }
        return sum;
    }

    private static long listProduct(PuzzList list) {
        if (list.isEmpty()) return 1;
        long product = 1;
        for (int i = 0; i < list.size(); i++) {
            product *= toLong(list.get(i));
        }
        return product;
    }

    private static long listMin(PuzzList list) {
        if (list.isEmpty()) throw new PuzzLangException("min() on empty list");
        long min = toLong(list.first());
        for (int i = 1; i < list.size(); i++) {
            min = Math.min(min, toLong(list.get(i)));
        }
        return min;
    }

    private static long listMax(PuzzList list) {
        if (list.isEmpty()) throw new PuzzLangException("max() on empty list");
        long max = toLong(list.first());
        for (int i = 1; i < list.size(); i++) {
            max = Math.max(max, toLong(list.get(i)));
        }
        return max;
    }

    private static long toLong(Object obj) {
        if (obj instanceof Long l) return l;
        if (obj instanceof Integer i) return i.longValue();
        if (obj instanceof Number n) return n.longValue();
        throw new PuzzLangException("expected number, got %s", obj.getClass().getSimpleName());
    }

    // ── Iteration ─────────────────────────────────────────────────────────────

    /**
     * Returns the java.lang.Iterable for a value — used by for-in loops.
     */
    @SuppressWarnings("unchecked")
    public static Iterable<Object> toIterable(Object val) {
        if (val instanceof PuzzRange r)              return (Iterable<Object>)(Iterable<?>) r;
        if (val instanceof PuzzRange.SteppedRange s) return (Iterable<Object>)(Iterable<?>) s;
        if (val instanceof PuzzList l)               return l;
        if (val instanceof Iterable<?> it)           return (Iterable<Object>) it;
        throw PuzzLangException.notIterable(val);
    }

    // ── Arithmetic ────────────────────────────────────────────────────────────

    public static Object add(Object a, Object b) {
        if (a instanceof Integer ia && b instanceof Integer ib) return ia + ib;
        if (a instanceof Long la && b instanceof Long lb) return la + lb;
        if (a instanceof Integer ia && b instanceof Long lb) return ia + lb;
        if (a instanceof Long la && b instanceof Integer ib) return la + ib;
        return String.valueOf(a) + String.valueOf(b);
    }

    public static Object sub(Object a, Object b) { return toInt(a) - toInt(b); }
    public static Object mul(Object a, Object b) { return toInt(a) * toInt(b); }

    public static Object div(Object a, Object b) {
        int d = toInt(b);
        if (d == 0) throw PuzzLangException.divisionByZero();
        return toInt(a) / d;
    }

    public static Object mod(Object a, Object b) {
        int d = toInt(b);
        if (d == 0) throw PuzzLangException.divisionByZero();
        return toInt(a) % d;
    }

    // ── Comparisons ───────────────────────────────────────────────────────────

    public static Object eq(Object a, Object b) {
        if (a == null) return b == null;
        return a.equals(b);
    }
    public static Object neq(Object a, Object b) { return !eq(a, b).equals(true); }
    public static Object lt(Object a, Object b)  { return toInt(a) <  toInt(b); }
    public static Object lte(Object a, Object b) { return toInt(a) <= toInt(b); }
    public static Object gt(Object a, Object b)  { return toInt(a) >  toInt(b); }
    public static Object gte(Object a, Object b) { return toInt(a) >= toInt(b); }

    // ── Truthiness ────────────────────────────────────────────────────────────

    public static boolean isTruthy(Object v) {
        if (v == null) return false;
        if (v instanceof Boolean b) return b;
        if (v instanceof Integer i) return i != 0;
        if (v instanceof Long l) return l != 0;
        if (v instanceof String s) return !s.isEmpty();
        if (v instanceof PuzzList pl) return !pl.isEmpty();
        return true;
    }

    // ── Conversion helpers ────────────────────────────────────────────────────

    public static int toInt(Object v) {
        if (v instanceof Integer i) return i;
        if (v instanceof Long l) return l.intValue();
        if (v instanceof String s) {
            try { return Integer.parseInt(s.trim()); }
            catch (NumberFormatException e) {
                throw new PuzzLangException("cannot convert '%s' to int", s);
            }
        }
        throw new PuzzLangException("cannot convert %s to int", v.getClass().getSimpleName());
    }

    public static String toString(Object v) {
        return String.valueOf(v);
    }
}
