package com.puzzlang.runtime;

import com.puzzlang.runtime.builtins.RangeBuiltins;

/**
 * PuzzRuntime — dynamic dispatch for all runtime operations.
 *
 * All methods take Object and return Object so they work with
 * INVOKESTATIC from our generated bytecode.
 *
 * Method dispatch is now delegated to MethodRegistry for extensibility.
 * Also handles String and PuzzList method calls directly.
 */
public class PuzzRuntime {

    // Shared registry instance (initialized lazily)
    private static volatile MethodRegistry registry;

    /**
     * Gets (or creates) the shared method registry.
     */
    public static MethodRegistry getRegistry() {
        if (registry == null) {
            synchronized (PuzzRuntime.class) {
                if (registry == null) {
                    registry = createDefaultRegistry();
                }
            }
        }
        return registry;
    }

    /**
     * Allows replacing the registry (useful for testing or custom configurations).
     */
    public static void setRegistry(MethodRegistry newRegistry) {
        synchronized (PuzzRuntime.class) {
            registry = newRegistry;
        }
    }

    private static MethodRegistry createDefaultRegistry() {
        MethodRegistry reg = new MethodRegistry();
        RangeBuiltins.register(reg);
        return reg;
    }

    // ── Range construction ────────────────────────────────────────────────────

    /** Called for  start..end  (exclusive) */
    public static Object makeRange(Object start, Object end) {
        return new PuzzRange(toInt(start), toInt(end), false);
    }

    /** Called for  start..=end  (inclusive) */
    public static Object makeRangeInclusive(Object start, Object end) {
        return new PuzzRange(toInt(start), toInt(end), true);
    }

    // ── Method dispatch ───────────────────────────────────────────────────────

    /**
     * Dispatches receiver.method(args) calls.
     *
     * Handles:
     *   - String methods (lines, paragraphs, split, trim, etc.)
     *   - PuzzList methods (count, first, last, get, join, etc.)
     *   - PuzzRange methods (via MethodRegistry)
     */
    public static Object callMethod(Object receiver, String method, Object... args) {
        // ── String methods ────────────────────────────────────────────────
        if (receiver instanceof String str) {
            return switch (method) {
                case "lines"      -> PuzzString.lines(str);
                case "paragraphs" -> PuzzString.paragraphs(str);
                case "split"      -> PuzzString.split(str, toString(args[0]));
                case "words"      -> PuzzString.words(str);
                case "chars"      -> PuzzString.chars(str);
                case "trim"       -> str.trim();
                case "length"     -> str.length();
                case "toInt"      -> PuzzString.toInt(str);
                case "upper"      -> str.toUpperCase();
                case "lower"      -> str.toLowerCase();
                case "startsWith" -> PuzzString.startsWith(str, toString(args[0]));
                case "endsWith"   -> PuzzString.endsWith(str, toString(args[0]));
                case "contains"   -> PuzzString.contains(str, toString(args[0]));
                case "replace"    -> PuzzString.replace(str, toString(args[0]), toString(args[1]));
                case "isEmpty"    -> str.isEmpty();
                case "get"        -> String.valueOf(str.charAt(toInt(args[0])));
                case "substring"  -> {
                    int start = toInt(args[0]);
                    if (args.length > 1) {
                        yield str.substring(start, toInt(args[1]));
                    }
                    yield str.substring(start);
                }
                default -> throw new PuzzLangException("String has no method '%s'", method);
            };
        }

        // ── PuzzList methods ──────────────────────────────────────────────
        if (receiver instanceof PuzzList list) {
            return switch (method) {
                case "count"    -> (long) list.size();
                case "length"   -> (long) list.size();
                case "size"     -> (long) list.size();
                case "first"    -> list.first();
                case "last"     -> list.last();
                case "get"      -> list.get(toInt(args[0]));
                case "join"     -> list.join(toString(args[0]));
                case "isEmpty"  -> list.isEmpty();
                case "reversed" -> list.reversed();
                case "contains" -> list.contains(args[0]);
                case "indexOf"  -> list.indexOf(args[0]);
                default -> throw new PuzzLangException("List has no method '%s'", method);
            };
        }

        // ── Delegate to MethodRegistry for other types (PuzzRange, etc.) ──
        return getRegistry().dispatch(receiver, method, args);
    }

    // ── Iteration ─────────────────────────────────────────────────────────────

    /**
     * Returns the java.lang.Iterable for a value — used by for-in loops.
     */
    @SuppressWarnings("unchecked")
    public static Iterable<Object> toIterable(Object val) {
        if (val instanceof PuzzRange r)              return (Iterable<Object>)(Iterable<?>) r;
        if (val instanceof PuzzRange.SteppedRange s) return (Iterable<Object>)(Iterable<?>) s;
        if (val instanceof PuzzList l)               return l;
        if (val instanceof Iterable<?> it)           return (Iterable<Object>) it;
        throw PuzzLangException.notIterable(val);
    }

    // ── Arithmetic ────────────────────────────────────────────────────────────

    public static Object add(Object a, Object b) {
        if (a instanceof Integer ia && b instanceof Integer ib) return ia + ib;
        if (a instanceof Long la && b instanceof Long lb) return la + lb;
        if (a instanceof Integer ia && b instanceof Long lb) return ia + lb;
        if (a instanceof Long la && b instanceof Integer ib) return la + ib;
        return String.valueOf(a) + String.valueOf(b);
    }

    public static Object sub(Object a, Object b) { return toInt(a) - toInt(b); }
    public static Object mul(Object a, Object b) { return toInt(a) * toInt(b); }

    public static Object div(Object a, Object b) {
        int d = toInt(b);
        if (d == 0) throw PuzzLangException.divisionByZero();
        return toInt(a) / d;
    }

    // ── Comparisons ───────────────────────────────────────────────────────────

    public static Object eq(Object a, Object b) {
        if (a == null) return b == null;
        return a.equals(b);
    }
    public static Object neq(Object a, Object b) { return !(Boolean) eq(a, b); }
    public static Object lt(Object a, Object b)  { return toInt(a) <  toInt(b); }
    public static Object lte(Object a, Object b) { return toInt(a) <= toInt(b); }
    public static Object gt(Object a, Object b)  { return toInt(a) >  toInt(b); }
    public static Object gte(Object a, Object b) { return toInt(a) >= toInt(b); }

    // ── Truth testing ─────────────────────────────────────────────────────────

    public static boolean isTruthy(Object val) {
        if (val == null)               return false;
        if (val instanceof Boolean b)  return b;
        if (val instanceof Integer i)  return i != 0;
        if (val instanceof Long l)     return l != 0;
        if (val instanceof String s)   return !s.isEmpty();
        if (val instanceof PuzzList l) return !l.isEmpty();
        return true;
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    public static int toInt(Object val) {
        if (val instanceof Integer i) return i;
        if (val instanceof Long l)    return l.intValue();
        if (val instanceof String s)  {
            try {
                return Integer.parseInt(s.trim());
            } catch (NumberFormatException e) {
                throw PuzzLangException.conversionFailed(s, "int");
            }
        }
        throw PuzzLangException.typeMismatch("int", val);
    }

    public static String toString(Object val) {
        return String.valueOf(val);
    }
}