package com.puzzlang.runtime;

import com.puzzlang.runtime.builtins.GridBuiltins;
import com.puzzlang.runtime.builtins.IntegerBuiltins;
import com.puzzlang.runtime.builtins.MathBuiltins;
import com.puzzlang.runtime.builtins.RangeBuiltins;

import java.util.Arrays;

/**
 * PuzzRuntime — dynamic dispatch for all runtime operations.
 *
 * All methods take Object and return Object so they work with
 * INVOKESTATIC from our generated bytecode.
 *
 * Handles:
 *   - Range construction: makeRange, makeRangeInclusive
 *   - Tuple construction: makeTuple
 *   - List construction: makeList, emptyList
 *   - Tuple operations: unpackTuple, isTupleOfSize, getTupleElements
 *   - Method dispatch: callMethod
 *   - Global functions: callFunction
 */
public class PuzzRuntime {

    // Shared registry instance (initialized lazily)
    private static volatile MethodRegistry registry;

    /**
     * Gets (or creates) the shared method registry.
     */
    public static MethodRegistry getRegistry() {
        if (registry == null) {
            synchronized (PuzzRuntime.class) {
                if (registry == null) {
                    registry = createDefaultRegistry();
                }
            }
        }
        return registry;
    }

    /**
     * Allows replacing the registry (useful for testing or custom configurations).
     */
    public static void setRegistry(MethodRegistry newRegistry) {
        synchronized (PuzzRuntime.class) {
            registry = newRegistry;
        }
    }

    private static MethodRegistry createDefaultRegistry() {
        MethodRegistry reg = new MethodRegistry();
        RangeBuiltins.register(reg);
        IntegerBuiltins.register(reg);
        GridBuiltins.register(reg);
        return reg;
    }

    // ══════════════════════════════════════════════════════════════════════════
    //  Range Construction
    // ══════════════════════════════════════════════════════════════════════════

    /** Called for start..end (exclusive) */
    public static Object makeRange(Object start, Object end) {
        return new PuzzRange(toInt(start), toInt(end), false);
    }

    /** Called for start..=end (inclusive) */
    public static Object makeRangeInclusive(Object start, Object end) {
        return new PuzzRange(toInt(start), toInt(end), true);
    }

    // ══════════════════════════════════════════════════════════════════════════
    //  Tuple Construction and Operations
    // ══════════════════════════════════════════════════════════════════════════

    /**
     * Create a tuple from an array of elements.
     * Called by bytecode for tuple literals: (a, b, c)
     */
    public static Object makeTuple(Object[] elements) {
        return new PuzzTuple(Arrays.asList(elements));
    }

    /**
     * Unpack a tuple into an array of elements.
     * Verifies size matches expected count.
     * Used for destructuring: let (x, y) = point
     */
    public static Object[] unpackTuple(Object value, int expectedSize) {
        if (value instanceof PuzzTuple tuple) {
            return tuple.unpack(expectedSize);
        }
        if (value instanceof PuzzList list) {
            // Also allow destructuring lists
            if (list.size() != expectedSize) {
                throw new PuzzLangException(
                        "cannot unpack list of size %d into %d variables",
                        list.size(), expectedSize);
            }
            Object[] result = new Object[expectedSize];
            for (int i = 0; i < expectedSize; i++) {
                result[i] = list.get(i);
            }
            return result;
        }
        throw new PuzzLangException(
                "cannot destructure %s - expected tuple or list",
                value.getClass().getSimpleName());
    }

    /**
     * Check if value is a tuple with exactly n elements.
     * Used for tuple pattern matching.
     */
    public static boolean isTupleOfSize(Object value, int size) {
        if (value instanceof PuzzTuple tuple) {
            return tuple.size() == size;
        }
        if (value instanceof PuzzList list) {
            return list.size() == size;
        }
        return false;
    }

    /**
     * Get elements of a tuple as an array.
     * Used for tuple pattern matching.
     */
    public static Object[] getTupleElements(Object value) {
        if (value instanceof PuzzTuple tuple) {
            return tuple.toArray();
        }
        if (value instanceof PuzzList list) {
            Object[] result = new Object[list.size()];
            for (int i = 0; i < list.size(); i++) {
                result[i] = list.get(i);
            }
            return result;
        }
        throw new PuzzLangException("expected tuple or list, got %s",
                value.getClass().getSimpleName());
    }

    // ══════════════════════════════════════════════════════════════════════════
    //  List Construction
    // ══════════════════════════════════════════════════════════════════════════

    /**
     * Create a list from an array of elements.
     * Called by bytecode for list literals: [a, b, c]
     */
    public static Object makeList(Object[] elements) {
        return new PuzzList(Arrays.asList(elements));
    }

    /**
     * Create an empty list.
     * Called by bytecode for empty list literal: []
     */
    public static Object emptyList() {
        return new PuzzList();
    }

    // ══════════════════════════════════════════════════════════════════════════
    //  Global Function Dispatch
    // ══════════════════════════════════════════════════════════════════════════

    /**
     * Dispatches global function calls: name(arg0, arg1, ...)
     */
    public static Object callFunction(String name, Object... args) {
        return MathBuiltins.call(name, args);
    }

    // ══════════════════════════════════════════════════════════════════════════
    //  Method Dispatch
    // ══════════════════════════════════════════════════════════════════════════

    /**
     * Dispatches receiver.method(args) calls.
     *
     * Handles:
     *   - String methods (lines, paragraphs, split, trim, upper, lower, etc.)
     *   - PuzzList methods (count, first, last, get, join, etc.)
     *   - PuzzTuple methods (get, first, second, size, etc.)
     *   - PuzzGrid methods (via registry)
     *   - Integer methods (via registry)
     *   - PuzzRange methods (via registry)
     */
    public static Object callMethod(Object receiver, String method, Object... args) {
        if (receiver == null) {
            throw new PuzzLangException("cannot call method '%s' on null", method);
        }

        // ── String methods ────────────────────────────────────────────────
        if (receiver instanceof String str) {
            return switch (method) {
                case "lines"      -> PuzzString.lines(str);
                case "paragraphs" -> PuzzString.paragraphs(str);
                case "split"      -> PuzzString.split(str, toString(args[0]));
                case "words"      -> PuzzString.words(str);
                case "chars"      -> PuzzString.chars(str);
                case "trim"       -> str.trim();
                case "length"     -> str.length();
                case "count"      -> countSubstring(str, toString(args[0]));
                case "toInt"      -> PuzzString.toInt(str);
                case "to_int"     -> PuzzString.toInt(str);
                case "upper"      -> str.toUpperCase();
                case "lower"      -> str.toLowerCase();
                case "startsWith" -> PuzzString.startsWith(str, toString(args[0]));
                case "starts_with" -> PuzzString.startsWith(str, toString(args[0]));
                case "endsWith"   -> PuzzString.endsWith(str, toString(args[0]));
                case "ends_with"  -> PuzzString.endsWith(str, toString(args[0]));
                case "contains"   -> PuzzString.contains(str, toString(args[0]));
                case "replace"    -> PuzzString.replace(str, toString(args[0]), toString(args[1]));
                case "isEmpty"    -> str.isEmpty();
                case "is_empty"   -> str.isEmpty();
                case "get"        -> String.valueOf(str.charAt(toInt(args[0])));
                case "substring"  -> {
                    int start = toInt(args[0]);
                    if (args.length > 1) {
                        yield str.substring(start, toInt(args[1]));
                    }
                    yield str.substring(start);
                }
                case "from_base"  -> {
                    int base = toInt(args[0]);
                    if (base < 2 || base > 36) {
                        throw new PuzzLangException("from_base requires base between 2 and 36, got %d", base);
                    }
                    yield Long.parseLong(str, base);
                }
                case "reverse"    -> new StringBuilder(str).reverse().toString();
                case "repeat"     -> str.repeat(toInt(args[0]));
                
                // Grid parsing
                case "grid" -> {
                    if (args.length == 0) {
                        yield PuzzGrid.fromString(str);
                    } else if (args.length == 1 && "toInt".equals(String.valueOf(args[0]))) {
                        // grid(toInt) - parse each char as integer
                        yield PuzzGrid.fromString(str, c -> {
                            try {
                                return Integer.parseInt(c);
                            } catch (NumberFormatException e) {
                                return c; // Keep as string if not a number
                            }
                        });
                    } else {
                        throw new PuzzLangException("grid() takes 0 or 1 arguments");
                    }
                }
                
                default -> throw new PuzzLangException("String has no method '%s'", method);
            };
        }

        // ── PuzzList methods ──────────────────────────────────────────────
        if (receiver instanceof PuzzList list) {
            return switch (method) {
                case "count" -> {
                    // count() returns size, count(value) returns occurrences
                    if (args.length == 0) {
                        yield (long) list.size();
                    } else {
                        yield (long) list.countOccurrences(args[0]);
                    }
                }
                case "length"   -> (long) list.size();
                case "size"     -> (long) list.size();
                case "first"    -> list.first();
                case "last"     -> list.last();
                case "get"      -> list.get(toInt(args[0]));
                case "join"     -> list.join(toString(args[0]));
                case "isEmpty"  -> list.isEmpty();
                case "is_empty" -> list.isEmpty();
                case "reversed" -> list.reversed();
                case "contains" -> list.contains(args[0]);
                case "indexOf"  -> list.indexOf(args[0]);
                case "index_of" -> list.indexOf(args[0]);
                case "sum"      -> listSum(list);
                case "product"  -> listProduct(list);
                case "min"      -> listMin(list);
                case "max"      -> listMax(list);
                case "sorted"   -> list.sorted();
                case "unique"   -> list.unique();
                default -> throw new PuzzLangException("List has no method '%s'", method);
            };
        }

        // ── PuzzTuple methods ─────────────────────────────────────────────
        if (receiver instanceof PuzzTuple tuple) {
            return switch (method) {
                case "get"      -> tuple.get(toInt(args[0]));
                case "first"    -> tuple.first();
                case "second"   -> tuple.second();
                case "third"    -> tuple.third();
                case "last"     -> tuple.last();
                case "size"     -> (long) tuple.size();
                case "count"    -> (long) tuple.size();
                case "toList"   -> tuple.toList();
                case "to_list"  -> tuple.toList();
                default -> throw new PuzzLangException("Tuple has no method '%s'", method);
            };
        }

        // ── PuzzGrid methods (delegated to registry) ──────────────────────
        if (receiver instanceof PuzzGrid) {
            return getRegistry().dispatch(receiver, method, args);
        }

        // ── Delegate to registry for other types ──────────────────────────
        return getRegistry().dispatch(receiver, method, args);
    }

    // ══════════════════════════════════════════════════════════════════════════
    //  Helper Methods
    // ══════════════════════════════════════════════════════════════════════════

    private static int countSubstring(String str, String sub) {
        if (sub.isEmpty()) return 0;
        int count = 0;
        int idx = 0;
        while ((idx = str.indexOf(sub, idx)) != -1) {
            count++;
            idx += sub.length();
        }
        return count;
    }

    private static long listSum(PuzzList list) {
        long sum = 0;
        for (int i = 0; i < list.size(); i++) {
            sum += toLong(list.get(i));
        }
        return sum;
    }

    private static long listProduct(PuzzList list) {
        if (list.isEmpty()) return 1;
        long product = 1;
        for (int i = 0; i < list.size(); i++) {
            product *= toLong(list.get(i));
        }
        return product;
    }

    private static long listMin(PuzzList list) {
        if (list.isEmpty()) throw new PuzzLangException("min() on empty list");
        long min = toLong(list.first());
        for (int i = 1; i < list.size(); i++) {
            min = Math.min(min, toLong(list.get(i)));
        }
        return min;
    }

    private static long listMax(PuzzList list) {
        if (list.isEmpty()) throw new PuzzLangException("max() on empty list");
        long max = toLong(list.first());
        for (int i = 1; i < list.size(); i++) {
            max = Math.max(max, toLong(list.get(i)));
        }
        return max;
    }

    private static long toLong(Object obj) {
        if (obj instanceof Long l) return l;
        if (obj instanceof Integer i) return i.longValue();
        if (obj instanceof Number n) return n.longValue();
        throw new PuzzLangException("expected number, got %s", obj.getClass().getSimpleName());
    }

    // ══════════════════════════════════════════════════════════════════════════
    //  Iteration
    // ══════════════════════════════════════════════════════════════════════════

    @SuppressWarnings("unchecked")
    public static Iterable<Object> toIterable(Object val) {
        if (val instanceof PuzzRange r)              return (Iterable<Object>)(Iterable<?>) r;
        if (val instanceof PuzzRange.SteppedRange s) return (Iterable<Object>)(Iterable<?>) s;
        if (val instanceof PuzzList l)               return l;
        if (val instanceof PuzzTuple t)              return t;
        if (val instanceof PuzzGrid g)               return g;
        if (val instanceof Iterable<?> it)           return (Iterable<Object>) it;
        throw PuzzLangException.notIterable(val);
    }

    // ══════════════════════════════════════════════════════════════════════════
    //  Arithmetic
    // ══════════════════════════════════════════════════════════════════════════

    public static Object add(Object a, Object b) {
        if (a instanceof Integer ia && b instanceof Integer ib) return ia + ib;
        if (a instanceof Long la && b instanceof Long lb) return la + lb;
        if (a instanceof Integer ia && b instanceof Long lb) return ia + lb;
        if (a instanceof Long la && b instanceof Integer ib) return la + ib;
        return String.valueOf(a) + String.valueOf(b);
    }

    public static Object sub(Object a, Object b) {
        if (a instanceof Integer ia && b instanceof Integer ib) return ia - ib;
        if (a instanceof Long la && b instanceof Long lb) return la - lb;
        if (a instanceof Integer ia && b instanceof Long lb) return ia - lb;
        if (a instanceof Long la && b instanceof Integer ib) return la - ib;
        throw new PuzzLangException("cannot subtract %s and %s",
                a.getClass().getSimpleName(), b.getClass().getSimpleName());
    }

    public static Object mul(Object a, Object b) {
        if (a instanceof Integer ia && b instanceof Integer ib) return ia * ib;
        if (a instanceof Long la && b instanceof Long lb) return la * lb;
        if (a instanceof Integer ia && b instanceof Long lb) return ia * lb;
        if (a instanceof Long la && b instanceof Integer ib) return la * ib;
        throw new PuzzLangException("cannot multiply %s and %s",
                a.getClass().getSimpleName(), b.getClass().getSimpleName());
    }

    public static Object div(Object a, Object b) {
        if (a instanceof Integer ia && b instanceof Integer ib) return ia / ib;
        if (a instanceof Long la && b instanceof Long lb) return la / lb;
        if (a instanceof Integer ia && b instanceof Long lb) return ia / lb;
        if (a instanceof Long la && b instanceof Integer ib) return la / ib;
        throw new PuzzLangException("cannot divide %s and %s",
                a.getClass().getSimpleName(), b.getClass().getSimpleName());
    }

    public static Object mod(Object a, Object b) {
        if (a instanceof Integer ia && b instanceof Integer ib) return ia % ib;
        if (a instanceof Long la && b instanceof Long lb) return la % lb;
        if (a instanceof Integer ia && b instanceof Long lb) return ia % lb;
        if (a instanceof Long la && b instanceof Integer ib) return la % ib;
        throw new PuzzLangException("cannot modulo %s and %s",
                a.getClass().getSimpleName(), b.getClass().getSimpleName());
    }

    // ══════════════════════════════════════════════════════════════════════════
    //  Comparison
    // ══════════════════════════════════════════════════════════════════════════

    public static Object eq(Object a, Object b) {
        return equals(a, b);
    }

    public static Object neq(Object a, Object b) {
        return !equals(a, b);
    }

    public static boolean equals(Object a, Object b) {
        if (a == null && b == null) return true;
        if (a == null || b == null) return false;
        // Handle numeric comparison
        if (a instanceof Number && b instanceof Number) {
            return ((Number) a).longValue() == ((Number) b).longValue();
        }
        return a.equals(b);
    }

    public static Object lt(Object a, Object b) {
        return compare(a, b) < 0;
    }

    public static Object lte(Object a, Object b) {
        return compare(a, b) <= 0;
    }

    public static Object gt(Object a, Object b) {
        return compare(a, b) > 0;
    }

    public static Object gte(Object a, Object b) {
        return compare(a, b) >= 0;
    }

    @SuppressWarnings("unchecked")
    private static int compare(Object a, Object b) {
        if (a instanceof Number na && b instanceof Number nb) {
            return Long.compare(na.longValue(), nb.longValue());
        }
        if (a instanceof Comparable ca && b instanceof Comparable) {
            return ca.compareTo(b);
        }
        throw new PuzzLangException("cannot compare %s and %s",
                a.getClass().getSimpleName(), b.getClass().getSimpleName());
    }

    // ══════════════════════════════════════════════════════════════════════════
    //  Truthiness
    // ══════════════════════════════════════════════════════════════════════════

    public static boolean isTruthy(Object val) {
        if (val == null) return false;
        if (val instanceof Boolean b) return b;
        if (val instanceof Integer i) return i != 0;
        if (val instanceof Long l) return l != 0;
        if (val instanceof String s) return !s.isEmpty();
        if (val instanceof PuzzList l) return !l.isEmpty();
        if (val instanceof PuzzTuple t) return !t.isEmpty();
        return true;
    }

    // ══════════════════════════════════════════════════════════════════════════
    //  Type Conversion
    // ══════════════════════════════════════════════════════════════════════════

    public static int toInt(Object obj) {
        if (obj instanceof Integer i) return i;
        if (obj instanceof Long l) return l.intValue();
        if (obj instanceof String s) return Integer.parseInt(s.trim());
        throw new PuzzLangException("cannot convert %s to int",
                obj.getClass().getSimpleName());
    }

    public static String toString(Object obj) {
        return String.valueOf(obj);
    }
}
